apiVersion: 1

datasources:
  - name: RTNO ClickHouse
    uid: rtno-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: rtno
      username: default
